name: 'Chrome extension upload action'
description: 'upload & publish extensions to the Chrome Web Store'
author: 'mnao305'
branding:
  color: blue
  icon: upload-cloud
inputs:
  file-path:
    description: 'path & filename to a zip file'
    required: true
  extension-id:
    description: 'extension id'
    required: true
  client-id:
    description: 'client id'
    required: true
  client-secret:
    description: 'client secret'
    required: true
  refresh-token:
    description: 'refresh token'
    required: true
  glob:
    description: 'if true the file can be a glob pattern'
    required: false
    default: "false"
  publish:
    description: 'if true package will be automatically published'
    required: false
    default: "true"
  publish-target:
    required: false
    description: 'target of publish (`default` or `trustedTesters`)'
    default: "default"
runs:
  using: 'node20'
  main: 'dist/index.js'
